title: My GitHub Page
description: Welcome to my GitHub

remote_theme: pages-themes/tactile@v0.2.0

plugins:
  - jekyll-remote-theme


navigation:
- text: Home
  url: /
- text: About
  url: /about
- text: Contact
  url: /contact
